name: localization
description: Package to simplify the package translation.
version: 1.1.0
homepage: https://github.com/davidsdearaujo/localization

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - test/assets/lang/
    - test/assets/lang2/